version: '3.9'

services:
  app:
    build: ./docker
    image: php-8.2/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
    depends_on:
      - mysql
    networks:
      - network

  mysql:
    image: mysql:8.0
    ports:
      - "3399:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'appDB'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
    volumes:
      - ./docker/mysql/db:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - network
networks:
  network:
    driver: bridge